platform :ios, '14.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'Plugin' do
  capacitor_pods
  pod 'LiveKitClient', :git => 'https://github.com/livekit/client-sdk-swift.git', :branch => 'main'
  pod 'KeychainAccess'
  pod 'SFSafeSymbols', '~> 4.1.1'
  pod 'SwiftProtobuf', '~> 1.0'
end

target 'PluginTests' do
  capacitor_pods
end
